### ISSUE TITLE
Add underline support

### ISSUE THREAD

**Issue by Bartemis** [catcombo/jira2markdown#14]
Would be nice to add underline support.
To do it now you can use the following code:

```python
import jira2markdown
from jira2markdown.elements import MarkupElements
from jira2markdown.markup.text_effects import QuotedElement, Underline

text = "This is a +test+"


class CustomUnderline(QuotedElement):
    TOKEN = "+"
    QUOTE_CHAR = "<u>"
    END_QUOTE_CHAR = "</u>"


elements = MarkupElements()
elements.replace(Underline, CustomUnderline)

print(jira2markdown.convert(text, elements=elements))

```

**Comment by catcombo** [comment]
Hi @Bartemis, thank you for you proposal. Could you please test updated code with your test cases before I publish it? See https://github.com/catcombo/jira2markdown/pull/15

**Comment by Bartemis** [comment]
Hi @catcombo, sure I will add some test cases for you

**Comment by catcombo** [comment]
@Bartemis great, thank you! I'll merge the PR and will publish a new version.
