### ISSUE TITLE
Examples of overriding various markup to "plain text"?

### ISSUE THREAD

**Issue by eddyg** [catcombo/jira2markdown#16]
First, thanks for a great library! 🎉

I'd like to be able to convert more elements to "plain text", for example, when it sees `{color:red}Red Text{color}`, I'd like the conversion to only have `Red Text`.

I'm not familiar with pyparsing, so I'm wondering if you have suggestions on the "best" way to override the various classes in the `markup` directory.

Perhaps you can provide some examples of how to convert some of the various classes of markup to _"just text"_?

**Comment by catcombo** [comment]
Hi @eddyg !

Thank you for your kind words!

You can use the element parser class you want to change the behavior of as a base class. Then you need to update ether `action` method (if exists) or `expr` method. In the case of the color tag, the code may look like this:

```python
from pyparsing import ParseResults

from jira2markdown import convert
from jira2markdown.elements import MarkupElements
from jira2markdown.markup.text_effects import Color


class CustomColor(Color):
    def action(self, tokens: ParseResults) -> str:
        return self.inline_markup.transform_string(tokens.text)


elements = MarkupElements()
elements.replace(Color, CustomColor)

print(convert("{color:red}Red Text{color}", elements=elements))
```
It's hard to provide a universal solution. So if you have any more questions, feel free to ask.

**Comment by eddyg** [comment]
Ah, fantastic!

Thanks for the example — I had been able to override some simple inline examples by just setting `QUOTE_CHAR` and `END_QUOTE_CHAR` in the custom classes, but wasn't sure what was needed for a more complex token. Your example helps a lot.

I'll close this for now. Thanks again! 👍
