### ISSUE TITLE
Add conversion for sub/super-script

### ISSUE THREAD

**Issue by zyv** [catcombo/jira2markdown#2]
We use `^superscript^` and `~subscript~` in our projects.

Could you please add translation according to the following rules:

1. If unicode conversion of the complete marked text possible, then do it: https://gist.github.com/molomby/9bc092e4a125f529ae362de7e46e8176 
2. If no unicode conversion is possible, then wrap in `<sup>` & `<sub>` tags

Thanks!

**Comment by catcombo** [comment]
I vote for the second rule only. The first one needs much more attention to implement and support:

1. Create mapping of all available characters and it's subscript/superscript counterparts. Need to keep the mapping up to date as the new unicode sub/super-script characters are added.
2. After conversion with [str.translate](https://docs.python.org/3/library/stdtypes.html#str.translate) need to compare it char by char with the original string to confirm the 100% conversion. At the moment, I don't know how to implement this efficiently.

**Comment by zyv** [comment]
In as far as mapping is concerned, I have linked a good one and we can assume nothing changes in the future in the relevant code planes.

As to comparison, I though that's actually quite easy:

```python
FROM = "..."
TO = "..."

translated = content.translate(str.maketrans(FROM, TO))

if all(src != dst for src, dst in zip(content, translated)):
    return content
else:
    return f"<sup>{content}</sup>"
```

We have enough cores to not to care about efficiency :)

**Comment by catcombo** [comment]
Ok, I am ready to exchange efficiency for beautiful and concise code :)

**Comment by zyv** [comment]
👍

**Comment by catcombo** [comment]
I can't help thinking this solution will lead me to the unpredictable bugs. I would prefer to implement the simplest solution so that you can extend it as you see fit.

**Comment by zyv** [comment]
Fine, I can live with that, thanks!
