### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by PydImmodvisor** [catcombo/jira2markdown#23]
Hi, 

First, thanks for this repo that is was I was looking for ! 

Hi installed it with pip (python 3.8.10)

When running I got : 
```
Traceback (most recent call last):
  File "/home/pyd/Code/Jira-to-wikijs/test.py", line 1, in <module>
    from jira2markdown import convert
  File "/home/pyd/.local/lib/python3.8/site-packages/jira2markdown/__init__.py", line 1, in <module>
    from .parser import convert  # noqa
  File "/home/pyd/.local/lib/python3.8/site-packages/jira2markdown/parser.py", line 7, in <module>
    ParserElement.set_default_whitespace_chars("")
AttributeError: type object 'ParserElement' has no attribute 'set_default_whitespace_chars'
```
My test file is very easy I used the example you provided : 
```
from jira2markdown import convert
print(convert("Some *Jira text* formatting [example|https://example.com]."))
```

Do you know what could have possibly go wrong ?

**Comment by catcombo** [comment]
Hello @PydImmodvisor!

Thanks for starting using `jira2markdown`!

I tried to reproduce your problem, but I wasn't successful with that:
```bash
> pyenv install 3.8.10
> mkdir jira2markdown-attribute-error
> cd jira2markdown-attribute-error
> poetry init
> poetry env use ~/.pyenv/versions/3.8.10/bin/python
> poetry install
> poetry add jira2markdown
> poetry shell
(jira2markdown-attribute-error-py3.8) > python
Python 3.8.10 (default, Nov 23 2023, 09:01:35) 
[GCC 13.2.1 20231011 (Red Hat 13.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jira2markdown import convert
>>> print(convert("Some *Jira text* formatting [example|https://example.com]."))
Some **Jira text** formatting [example](https://example.com).
```

> AttributeError: type object 'ParserElement' has no attribute 'set_default_whitespace_chars'

This line looks suspicious to me. It seems that `pyparsing` library, which `jira2markdown` uses under the hood, is version 2.x instead of 3.x. How did you install `jira2markdown`? Did you use `pip` or `poetry`?

**Comment by PydImmodvisor** [comment]
Hi, 

![Capture d’écran du 2023-11-23 08-07-23](https://github.com/catcombo/jira2markdown/assets/151768698/2b6b4b31-b8cd-4cdf-a0b2-6a4fbe7a11f9)

Yes you are right pyparsing is 2.x and I'm using pip.

What python version would you recommend for using jira2markdown ?

**Comment by catcombo** [comment]
> What python version would you recommend for using jira2markdown ?

`jira2markdown` supports Python version from 3.7 and higher. I personally prefer to use one of the latest Python versions to get access to the latest language features. For now, it's 3.11. But if Python 3.8 is enough for you, then just use it.

> Yes you are right pyparsing is 2.x and I'm using pip.

You can run `pip install -U pyparsing` to upgrade `pyparsing` to the latest version. Or maybe the better option will be to start using some of the dependency managers (e.g. https://python-poetry.org/docs/). It resolves dependency conflicts for you and does a lot of other useful things, like creating a virtual environment for each project.

**Comment by PydImmodvisor** [comment]
Hi, updating pyparsing worked. Thanks !
