### ISSUE TITLE
Emphasis text

### ISSUE THREAD

**Issue by kumy** [catcombo/jira2markdown#26]
Hi @catcombo 

regarding emphasis, the readme show that using `+foo+` will be rendered as `foo`
![image](https://github.com/user-attachments/assets/a0ec0279-ea3f-4535-9691-0576d61aea09)

However I found that it renders as `<u>foo</u>`. The [Unit Tests](https://github.com/catcombo/jira2markdown/blob/master/tests/markup/test_text_effects.py#L69) also confirm that as of the [code](https://github.com/catcombo/jira2markdown/blob/master/jira2markdown/markup/text_effects.py#L85-L88)

```
class TestUnderline:
    def test_basic_conversion(self):
        assert convert("inside +some long+ text") == "inside <u>some long</u> text"
```

I personally think it should be rendered as `*foo*` (or `_foo_`) as stated in [YouTrack Markdown](https://www.jetbrains.com/help/youtrack/server/youtrack-markdown-syntax-issues.html#characters)

![image](https://github.com/user-attachments/assets/50bbb633-45c5-48f7-9915-a58c183a316b)

I'll try to provide a PR

Thanks!

**Comment by kumy** [comment]
@catcombo Here is a [PR](https://github.com/catcombo/jira2markdown/pull/27) :pray:

**Comment by catcombo** [comment]
Hi @kumy!

Thank you very much for the detailed issue and the prepared PR! But I think converting `+text+` to an emphasis text is not completely correct. According to https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all `+text+` should be considered as inserted. Most browsers usually underline inserted text. Unfortunately, YouTrack doesn't render `ins` tag at all.

![image](https://github.com/user-attachments/assets/b7fe5158-e557-4fca-bf0f-63845ef2e623)

So the only way to make it visually compatible with the Jira renderer is to use `<u>` tag.
