### ISSUE TITLE
Add {panel} translation as block quote

### ISSUE THREAD

**Issue by zyv** [catcombo/jira2markdown#3]

**Comment by catcombo** [comment]
I thought the `panel` token is closer in meaning to `code` block rather than quote. Except that the `panel` allows a text formatting.

**Comment by zyv** [comment]
Yes, correct - panel allows text formatting, but it's meaning is not something like code block, but rather a block quote. Only by contrast with normal quote, instead of being formatted with an indentation, Jira shows a box around it.

One could also translate it as a `<div class="jira-panel">...</div>` and write custom CSS styles, which would be more flexible, but in the context of ticket system migration it is in my opinion easier and more meaningful to simply translate it as a quote (as Markdown quotes allow formatting).

**Comment by catcombo** [comment]
I want to highlight the panel title with heading:
```
{panel:title=My Title}
Some text with a title
{panel}
```
will be converted to
```
> ## My Title
> Some text with a title
```
What you think? Or maybe use bold markup for title?

**Comment by zyv** [comment]
I think that bold markup is better, because we don't know at which structural level the panel will be rendered.
