### ISSUE TITLE
image with properties

### ISSUE THREAD

**Issue by vasokot** [catcombo/jira2markdown#34]
Currently youtrack has this syntax `![Text](youtrack.svg){width=50 height=50}` and not support HTML Tags

How i can convert Jira markup `!image.jpg|width=300, height=200!` to `![](image.jpg){width=300 height=200}` ?

**Comment by vasokot** [comment]
See PR: https://github.com/catcombo/jira2markdown/pull/35

**Comment by catcombo** [comment]
Hi @vasokot !

Thank you for the issue. I cannot confirm your statement that YouTrack doesn't support image tags. I used the following code for tests, and the image has been rendered correctly:
```html
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/208px-Markdown-mark.svg.png" width="100">
```
What YouTrack version do you use? I'm not against your changes. Just want to understand why it doesn't work for you.

**Comment by vasokot** [comment]
I get comment from jira and send it to youtrack
image at this comment attached, not url, so i have `!image.jpg|width=300, height=200!` and when it goes to <img src="image.jpg" width="300" height="200" />
it show nothing:
![изображение](https://github.com/user-attachments/assets/ab927181-2f67-4a6d-89e8-2934685da304)

**Comment by catcombo** [comment]
You're right. I can confirm it. Thank you for finding and reporting this problem. Finish the PR and I'll deploy a new version immediately after that.

**Comment by catcombo** [comment]
PR has been merged. New package version is available on PyPI. Thank you!
