### ISSUE TITLE
`{noformat}` should accept the same parameters as `{panel}`

### ISSUE THREAD

**Issue by monate** [catcombo/jira2markdown#5]
Hello,
Thanks for this very convenient tool!

When parameters are used with the `{noformat}` tag, there are some mis-conversions.
As documented by https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced:

> All the optional parameters of {panel} macro are valid for {noformat} too.

The current implementation does not recognize the `{noformat}` tag at all when there is a parameter.

**Comment by catcombo** [comment]
Hey @monate, thanks for using jira2markdown!

Thank you for information about the issue with `noformat` tag. I've prepared the PR that should fix this problem. Could you please test it on your data?

**Comment by monate** [comment]
I have no easy way to test the PR but here is my original snippet:
```
{code:C++|title=test.cpp}
static bool hit = false;

struct Foo {
    int x;
};

struct Bar: virtual Foo {
    int y;
    Bar(): Bar(2) { }
    Bar(int) { hit = true; }
};

struct Baz: Bar {
    int z;
};

int
main()
{
    Baz b;
    //@ assert hit == true;
    return hit;
}
{code}

{noformat:title=tis-analyzer++ --interpreter test.cpp}
test.cpp:21:[value] warning: Assertion got status invalid (stopping propagation)
                 stack: main
[value] user error: Degeneration occurred:
                    results are not correct for lines of code that can be reached from the degeneration point.
{noformat}
```
