### ISSUE TITLE
ListIndent missing abstract method _generateDefaultName

### ISSUE THREAD

**Issue by Eureuka2013** [catcombo/jira2markdown#8]
I believe pyparser is requiring ListIndent to implement _generateDefaultName, per the following error received:

`...
    temp = jira2markdown.convert(text)
  File "/home/.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/parser.py", line 18, in convert
    markup << elements.expr(inline_markup, markup, usernames, elements)
  File "/home/.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/elements.py", line 64, in expr
    return MatchFirst([
  File "/home/.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/elements.py", line 65, in <listcomp>
    element(inline_markup=inline_markup, markup=markup, usernames=usernames).expr
  File "/home/.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/markup/lists.py", line 85, in expr
    + ListIndent(self.indent_state, self.tokens)
TypeError: Can't instantiate abstract class ListIndent with abstract method _generateDefaultName`

**Comment by catcombo** [comment]
Hey @Eureuka2013, could you please post the original Jira text that you tried to convert, so that I can use it to reproduce the problem on my computer?

**Comment by Eureuka2013** [comment]
Apologies, went camping for the long weekend. Here is test code:

`    def test_confirm_list_indent_error_with_jira2markdown(self):
        text = '''
        1. List Item Numero Uno
        2. List Item Numero Dos
        '''
>       temp = jira2markdown.convert(text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/parser.py:18: in convert
    markup << elements.expr(inline_markup, markup, usernames, elements)
../../../.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/elements.py:64: in expr
    return MatchFirst([
../../../.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/elements.py:65: in <listcomp>
    element(inline_markup=inline_markup, markup=markup, usernames=usernames).expr
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <jira2markdown.markup.lists.UnorderedList object at 0x7fc64b698c70>

    @property
    def expr(self) -> ParserElement:
        NL = LineEnd()
        LIST_BREAK = NL + Optional(White(" \t")) + NL | StringEnd()
        IGNORE = BlockQuote(**self.init_kwargs).expr | Panel(**self.init_kwargs).expr | Color(**self.init_kwargs).expr
        ROW = LineStart() + Combine(
            Optional(self.nested_token, default="")
>           + ListIndent(self.indent_state, self.tokens)
            + SkipTo(NL + Char(self.nested_token + self.tokens) | LIST_BREAK, ignore=IGNORE)
            + Optional(NL),
        )
E       TypeError: Can't instantiate abstract class ListIndent with abstract method _generateDefaultName

../../../.conda/envs/operations/lib/python3.10/site-packages/jira2markdown/markup/lists.py:85: TypeError`

**Comment by catcombo** [comment]
It's a dependency issue. You use newest `pyparsing` version, I guess it's 3.0.9. But `jira2markdown` needs pyparsing>=2.4,<3.0. How did you install `jira2markdown`? This problem shouldn't happen if you install it with `pip` or `poetry`.

**Comment by Eureuka2013** [comment]
This is from the original gent, but he says he did pip install. fwiw:
```
pyparsing.__version__=3.0.4
```

We see in files here:
```
[package.dependencies]
pyparsing = ">=2.0.2,<3.0.5 || >3.0.5"
```

Thanks.

**Comment by catcombo** [comment]
This is partial output of the `poetry show -t` command to list project dependencies:
```
pyparsing 2.4.7 Python parsing module
pytest 6.2.5 pytest: simple powerful testing with Python
├── atomicwrites >=1.0
├── attrs >=19.2.0
├── colorama *
├── importlib-metadata >=0.12
│   ├── typing-extensions >=3.6.4 
│   └── zipp >=0.5 
├── iniconfig *
├── packaging *
│   └── pyparsing >=2.0.2,<3.0.5 || >3.0.5 
```
The line you found `pyparsing = ">=2.0.2,<3.0.5 || >3.0.5"` relates to `pytest` dependencies, not the project dependencies. You can also see `pyparsing` version on the line above. `2.4.7` fits the requirements for `pytest` and for `jira2markdown` requirements in `pyproject.toml`: `pyparsing = "^2.4"`.

One can also check `setup.py` inside `jira2markdown-0.2.1.tar.gz` archive on [PyPI](https://pypi.org/project/jira2markdown/#files). You will find the line `install_requires = ["pyparsing>=2.4,<3.0"]` which defines the project requirements.

I also created an empty virtual environment and ran `pip install jira2markdown`. Here is the list of installed packages (you can see the pyparsing version is the correct - 2.4.7):
```
>> pip install jira2markdown
Collecting jira2markdown
  Downloading jira2markdown-0.2.1-py3-none-any.whl (12 kB)
Collecting pyparsing<3.0,>=2.4
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 KB 1.1 MB/s eta 0:00:00
Installing collected packages: pyparsing, jira2markdown
Successfully installed jira2markdown-0.2.1 pyparsing-2.4.7

>> pip list                 
Package       Version
------------- -------
jira2markdown 0.2.1
pip           22.0.4
pyparsing     2.4.7
setuptools    62.1.0
wheel         0.37.1
```

So my suggestion is to create an empty virtual environment and install all dependencies in it. I guess in your case dependencies from other packages clashes with dependencies for `jira2markdown`. Also maybe `pyparsing` was updated manually or during installation of other package.
